# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x07\n\x05\x45mpty\">\n\x03msg\x12\r\n\x05nameD\x18\x01 \x01(\t\x12\r\n\x05nameR\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0b\n\x03ipD\x18\x04 \x01(\t2;\n\x04\x63hat\x12\x1a\n\nreceiveMsg\x12\x04.msg\x1a\x06.Empty\x12\x17\n\x07sendMsg\x12\x04.msg\x1a\x06.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_MSG = DESCRIPTOR.message_types_by_name['msg']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

msg = _reflection.GeneratedProtocolMessageType('msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:msg)
  })
_sym_db.RegisterMessage(msg)

_CHAT = DESCRIPTOR.services_by_name['chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=17
  _EMPTY._serialized_end=24
  _MSG._serialized_start=26
  _MSG._serialized_end=88
  _CHAT._serialized_start=90
  _CHAT._serialized_end=149
# @@protoc_insertion_point(module_scope)
